#!/usr/bin/env bash
# Verify system dependencies.
#
# Copyright (c) 2018 Cisco and/or its affiliates.
#
# This software is licensed to you under the terms of the Cisco Sample
# Code License, Version 1.0 (the "License"). You may obtain a copy of the
# License at
#
#                https://developer.cisco.com/docs/licenses
#
# All use of the material herein must be in accordance with the terms of
# the License. All rights not expressly granted by the License are
# reserved. Unless required by applicable law or agreed to separately in
# writing, software distributed under the License is distributed on an "AS
# IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
# or implied.
#
# AUTHOR(s): Chris Lunsford <chrlunsf@cisco.com>


set -e
cd "$(dirname "$0")/.."


# Project Requirements
requires_python_version="3"
minimum_python_version="3.5"


echo "==> Checking Python system requirements"
if ! python -c "import sys; sys.exit(0 if sys.version_info.major == int($requires_python_version) else 1)" || \
   ! python -c "import sys; sys.exit(0 if float(sys.version_info.major + sys.version_info.minor / 10) > float($minimum_python_version) else 1)"; then

    echo >&2 "PYTHON VERSION CHECK FAILED:  This project requires Python v$requires_python_version, with a minimum version of v$minimum_python_version."
    exit 1
fi
