#!/usr/bin/env bash
# Setup or reset the project to its initial state.
#
# Copyright (c) 2018 Cisco and/or its affiliates.
#
# This software is licensed to you under the terms of the Cisco Sample
# Code License, Version 1.0 (the "License"). You may obtain a copy of the
# License at
#
#                https://developer.cisco.com/docs/licenses
#
# All use of the material herein must be in accordance with the terms of
# the License. All rights not expressly granted by the License are
# reserved. Unless required by applicable law or agreed to separately in
# writing, software distributed under the License is distributed on an "AS
# IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
# or implied.
#
# AUTHOR(s): Chris Lunsford <chrlunsf@cisco.com>

set -e
cd "$(dirname "$0")/.."


# Process Script Arguments
for i in ${@}; do
    case ${i} in
        --dev)
        dev=true
        ;;

        *)
        echo "Unknown argument: $i"
        exit 1
        ;;
    esac
done


echo "==> Setting up / resetting project for initial use"

script/clean --deep

if [ ${dev} ]; then
    script/installdeps --dev
else
    script/installdeps
fi


# Perform additional tasks needed to prepare the project for use

# Setup configuration files

# Create environment files

# Setup database
